import json
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, roc_auc_score

# 1. Load the data
data_path = os.path.join(os.path.dirname(__file__), 'synthetic_events.json')
with open(data_path, 'r') as f:
    events = json.load(f)

# 2. Extract features exactly as expected by the TS application
feature_order = [
    "amount_inr",
    "is_retryable",
    "is_payment_failure",
    "is_checkout_abandon"
]

retryable_reasons = [
    "card_declined",
    "insufficient_funds",
    "issuer_unavailable",
    "network_error",
    "timeout",
]

records = []
for e in events:
    # TS extractor for amount_inr is e.amount (we can also use features.amount_inr from dataset)
    amount_inr = e['amount']
    
    # TS extractor for is_retryable is retryable.includes(e.raw_reason)
    is_retryable = 1 if e.get('raw_reason') in retryable_reasons else 0
    
    # TS extractor for is_payment_failure
    is_payment_failure = 1 if e.get('source_type') == 'payment_failure' else 0
    
    # TS extractor for is_checkout_abandon
    is_checkout_abandon = 1 if e.get('source_type') == 'checkout_abandon' else 0

    recovered = 1 if e.get('recovered') else 0

    records.append({
        "amount_inr": amount_inr,
        "is_retryable": is_retryable,
        "is_payment_failure": is_payment_failure,
        "is_checkout_abandon": is_checkout_abandon,
        "recovered": recovered
    })

df = pd.DataFrame(records)

# 3. Train / Test split
X = df[feature_order]
y = df['recovered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Train Logistic Regression
model = LogisticRegression(random_state=42, max_iter=1000)
model.fit(X_train, y_train)

# 5. Extract Coefficients
intercept = float(model.intercept_[0])
weights = [float(w) for w in model.coef_[0]]

coefficients_output = {
    "intercept": intercept,
    "weights": weights,
    "feature_order": feature_order
}

coeff_path = os.path.join(os.path.dirname(__file__), 'coefficients.json')
with open(coeff_path, 'w') as f:
    json.dump(coefficients_output, f, indent=2)

# 6. Evaluate Metrics on Test Set
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
auc = roc_auc_score(y_test, y_proba)

# 7. Write Metrics Output
metrics_content = f"""# Model Metrics

These metrics were generated by training a Logistic Regression on the `synthetic_events.json` dataset using a 80/20 train/test split.

| Metric | Value |
|--------|-------|
| **Precision** | {precision:.4f} |
| **Recall** | {recall:.4f} |
| **AUC** | {auc:.4f} |
"""

metrics_path = os.path.join(os.path.dirname(__file__), 'metrics.md')
with open(metrics_path, 'w') as f:
    f.write(metrics_content)

print(f"Successfully trained model and wrote coefficients to {coeff_path} and metrics to {metrics_path}.")
