/**
 * Port: EventRepository
 *
 * Persistence interface for all RiskEvent-related entities.
 * Adapters: adapters/postgres/ (real), adapters/mock/ (in-memory fake).
 *
 * Every write method that touches multiple tables (e.g. insert event + outbox)
 * is expressed as a single call so the adapter can wrap it in a transaction.
 */

import type {
  RiskEvent,
  Score,
  Decision,
  PolicyCheckRecord,
  ActionExecution,
  OutboxRow,
  AuditLogEntry,
  RiskGroup,
  SourceType,
  ExecutionResult,
} from "./types.js";

// ── Insert DTOs (id and timestamps are generated by the adapter) ───

export interface InsertRiskEvent {
  readonly dedupe_key: string;
  readonly merchant_id: string;
  readonly source_type: SourceType;
  readonly customer_id: string;
  readonly amount: number;
  readonly currency: string;
  readonly raw_reason: string | null;
}

export interface InsertScore {
  readonly event_id: string;
  readonly p_loss: number;
  readonly p_uplift: number;
  readonly expected_value: number;
  readonly cost_estimate: number;
}

export interface InsertDecision {
  readonly event_id: string;
  readonly root_cause_summary: string;
  readonly selected_action: string;
  readonly rationale: string;
}

export interface InsertPolicyCheck {
  readonly event_id: string;
  readonly check_name: string;
  readonly passed: boolean;
  readonly detail: string | null;
}

export interface InsertActionExecution {
  readonly event_id: string;
  readonly idempotency_key: string;
  readonly action: string;
  readonly attempt_number: number;
  readonly result: ExecutionResult;
}

export interface InsertOutboxRow {
  readonly event_id: string;
  readonly payload: unknown;
}

export interface InsertAuditLog {
  readonly event_id: string | null;
  readonly stage: string;
  readonly detail: unknown;
}

// ── Port interface ─────────────────────────────────────────────────

export interface EventRepository {
  // ── RiskEvent ──────────────────────────────────────────────────
  /**
   * Insert a risk event + outbox row atomically.
   * Returns the created event. If dedupe_key already exists, returns null
   * (deduplicated — no duplicate row created).
   */
  insertEventWithOutbox(
    event: InsertRiskEvent,
    outboxPayload: unknown,
  ): Promise<RiskEvent | null>;

  findEventById(id: string): Promise<RiskEvent | null>;
  findEventByDedupeKey(dedupeKey: string): Promise<RiskEvent | null>;

  /** List events that have not yet been scored. */
  findUnscoredEvents(): Promise<RiskEvent[]>;

  /** Set the holdout group for an event (once, at scoring time). */
  setGroup(eventId: string, group: RiskGroup): Promise<void>;

  // ── Score ──────────────────────────────────────────────────────
  insertScore(score: InsertScore): Promise<Score>;
  findScoreByEventId(eventId: string): Promise<Score | null>;

  /** List scored events that have not yet been allocated/skipped/parked. */
  findScoredUnallocatedEvents(): Promise<
    Array<{ event: RiskEvent; score: Score }>
  >;

  // ── Decision ───────────────────────────────────────────────────
  insertDecision(decision: InsertDecision): Promise<Decision>;
  findDecisionByEventId(eventId: string): Promise<Decision | null>;

  // ── PolicyCheck ────────────────────────────────────────────────
  insertPolicyCheck(check: InsertPolicyCheck): Promise<PolicyCheckRecord>;
  findPolicyChecksByEventId(eventId: string): Promise<PolicyCheckRecord[]>;

  // ── ActionExecution ────────────────────────────────────────────
  /**
   * Insert an action execution.  The idempotency_key is unique — if a row
   * with the same key already exists, returns null (no duplicate execution).
   */
  insertActionExecution(
    execution: InsertActionExecution,
  ): Promise<ActionExecution | null>;

  findActionExecutionsByEventId(eventId: string): Promise<ActionExecution[]>;
  findLatestExecution(eventId: string): Promise<ActionExecution | null>;

  /** Sum of action costs for a merchant today (for spend-cap check). */
  getMerchantDailySpend(merchantId: string, today: Date): Promise<number>;

  // ── Outbox ─────────────────────────────────────────────────────
  /** Fetch unpublished outbox rows, oldest first, up to `limit`. */
  findUnpublishedOutbox(limit: number): Promise<OutboxRow[]>;

  /** Mark a set of outbox rows as published (atomically). */
  markOutboxPublished(ids: string[]): Promise<void>;

  // ── AuditLog ───────────────────────────────────────────────────
  insertAuditLog(entry: InsertAuditLog): Promise<AuditLogEntry>;
  findAuditLogsByEventId(eventId: string): Promise<AuditLogEntry[]>;

  // ── State tracking ─────────────────────────────────────────────
  /**
   * Returns the current state of an event, derived from the latest
   * records in score/decision/policy_check/action_execution tables.
   * The state machine itself lives in domain/ — this is purely a read.
   */
  getCurrentState(eventId: string): Promise<string | null>;

  /** Persist the computed state for fast lookups / dashboarding. */
  updateState(eventId: string, state: string): Promise<void>;
}
